name:                ustax4h
version:             0.1.0.0
github:              "kaesler/ustax4h"
license:             BSD3
author:              "Kevin Esler"
maintainer:          "kevin.esler@gmail.com"
copyright:           "2021 Kevin Esler"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kaesler/RetirementModelHaskell#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- nonempty-containers
- time

library:
  source-dirs: src

executables:
  ustax4h-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ustax4h

tests:
  ustax4h-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ustax4h
    - hspec >=2.0.0
    - QuickCheck



